Repository go-gremlins/gremlins, pull requests merged in 2022-07, with the labels that each got.

#47 Deep source integration
  .deepsource.toml
  README.md
  coverage/coverage_test.go
  mutator/internal/tokenmutant.go
  mutator/mutator.go
  mutator/mutator_test.go
  report/report_test.go
Labels: s/M

#46 Make error logs go to STDERR (#44)
  cmd/gremlins/main.go
  log/log.go
  log/log_test.go
  report/report_test.go
Labels: c/enhancement, p/medium, s/M

#45 Make test timeout dynamic (#21)
  cmd/unleash.go
  coverage/coverage.go
  coverage/coverage_test.go
  mutator/mutator.go
  mutator/mutator_test.go
Labels: c/enhancement, p/medium, s/L

#51 Prepare for first release
  .goreleaser.yaml
  AUTHORS
  README.md
Labels: c/chore, s/L

#55 chores: migrate to go-gremlins organization
  .deepsource.toml
  .github/workflows/ci.yml
  .goreleaser.yaml
  README.md
  cmd/gremlins.go
  cmd/gremlins/main.go
  cmd/unleash.go
  coverage/coverage.go
  coverage/coverage_test.go
  coverage/profile_test.go
  go.mod
  log/log_test.go
  mutant/mutant_test.go
  mutator/internal/mappings.go
  mutator/internal/node_test.go
  mutator/internal/tokenmutant.go
  mutator/internal/tokenmutant_test.go
  mutator/mutator.go
  mutator/mutator_test.go
  mutator/workdir/workdir.go
  mutator/workdir/workdir_test.go
  report/report.go
  report/report_test.go
Labels: c/chore

#57 update fossa
  README.md
Labels: c/chore

#58 move packages in pkg
  cmd/gremlins/main.go
  cmd/unleash.go
  pkg/coverage/coverage.go
  pkg/coverage/coverage_test.go
  pkg/coverage/profile.go
  pkg/coverage/profile_test.go
  pkg/coverage/testdata/invalid/coverage
  pkg/coverage/testdata/valid/coverage
  pkg/log/log.go
  pkg/log/log_test.go
  pkg/mutant/mutant.go
  pkg/mutant/mutant_test.go
  pkg/mutator/internal/mappings.go
  pkg/mutator/internal/node.go
  pkg/mutator/internal/node_test.go
  pkg/mutator/internal/tokenmutant.go
  pkg/mutator/internal/tokenmutant_test.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/mutator/testdata/fixtures/add_go
  pkg/mutator/testdata/fixtures/dec_go
  pkg/mutator/testdata/fixtures/eql_go
  pkg/mutator/testdata/fixtures/geq_go
  pkg/mutator/testdata/fixtures/geq_land_true_go
  pkg/mutator/testdata/fixtures/gtr_go
  pkg/mutator/testdata/fixtures/illegal_go
  pkg/mutator/testdata/fixtures/inc_go
  pkg/mutator/testdata/fixtures/leq_go
  pkg/mutator/testdata/fixtures/lss_go
  pkg/mutator/testdata/fixtures/mul_go
  pkg/mutator/testdata/fixtures/negative_sub_go
  pkg/mutator/testdata/fixtures/neq_go
  pkg/mutator/testdata/fixtures/quo_go
  pkg/mutator/testdata/fixtures/rem_go
  pkg/mutator/testdata/fixtures/sub_go
  pkg/mutator/workdir/workdir.go
  pkg/mutator/workdir/workdir_test.go
  pkg/report/report.go
  pkg/report/report_test.go
Labels: c/chore, s/M

#61 reformat using goimports
  cmd/gremlins/main.go
  cmd/gremlins/main_test.go
  cmd/unleash.go
  pkg/coverage/coverage.go
  pkg/coverage/coverage_test.go
  pkg/coverage/profile_test.go
  pkg/log/log.go
  pkg/log/log_test.go
  pkg/mutant/mutant_test.go
  pkg/mutator/internal/mappings.go
  pkg/mutator/internal/node_test.go
  pkg/mutator/internal/tokenmutant.go
  pkg/mutator/internal/tokenmutant_test.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/mutator/workdir/workdir.go
  pkg/mutator/workdir/workdir_test.go
  pkg/report/report.go
  pkg/report/report_test.go
Labels: c/bug, s/M

#62 update MacOS install instructions
  README.md
Labels: c/chore, s/XS

#63 docs: update contributing
  CONTRIBUTING.md
  README.md
Labels: c/docs, s/L

#64 add more linters
  .golangci.yml
  cmd/unleash.go
  pkg/coverage/coverage.go
  pkg/coverage/coverage_test.go
  pkg/coverage/profile.go
  pkg/coverage/profile_test.go
  pkg/mutator/internal/node.go
  pkg/mutator/internal/tokenmutant.go
  pkg/mutator/internal/tokenmutant_test.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/mutator/workdir/workdir.go
  pkg/mutator/workdir/workdir_test.go
  pkg/report/report.go
Labels: c/chore, s/L

#70 docs: update project email
  CODE_OF_CONDUCT.md
Labels: c/chore, s/XS

#74 docs: update email address
  CODE_OF_CONDUCT.md
Labels: c/docs, s/XS

#76 chore: prevent CI from failing on coverage report
  .github/workflows/ci.yml
  Makefile
Labels: c/chore, s/XS

#75 Added Viper configuration (#31)
  README.md
  cmd/configuration/testdata/config1/.gremlins.yaml
  cmd/configuration/testdata/config2/.gremlins.yaml
  cmd/configuration/viper.go
  cmd/configuration/viper_test.go
  cmd/gremlins.go
  cmd/testdata/config1/.gremlins.yaml
  cmd/testdata/config2/.gremlins.yaml
  cmd/unleash.go
  go.mod
  go.sum
Labels: s/L

#78 Add custom label
  .github/dependabot.yml
Labels: c/chore, s/XS

#77 Make Gremlins work on Windows
  .github/workflows/ci.yml
  .goreleaser.yaml
  README.md
  cmd/unleash.go
  go.mod
  go.sum
  pkg/coverage/coverage.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/mutator/workdir/workdir_test.go
Labels: c/enhancement, s/M

#79 feat: add failure thresholds
  .gremlins.yaml
  Makefile
  README.md
  cmd/configuration/testdata/config1/.gremlins.yaml
  cmd/configuration/testdata/config2/.gremlins.yaml
  cmd/configuration/viper.go
  cmd/gremlins.go
  cmd/gremlins/main.go
  cmd/unleash.go
  configuration/configuration.go
  configuration/configuration_test.go
  configuration/testdata/config1/.gremlins.yaml
  configuration/testdata/config2/.gremlins.yaml
  go.mod
  go.sum
  internal/execution/execution.go
  internal/execution/execution_test.go
  pkg/coverage/coverage.go
  pkg/coverage/coverage_test.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/report/report.go
  pkg/report/report_test.go
Labels: c/feature, c/enhancement, s/XL

#82 feat: make mutant types switchable
  .gremlins.yaml
  cmd/gremlins.go
  cmd/gremlins_test.go
  cmd/internal/flags/flags.go
  cmd/internal/flags/flags_test.go
  cmd/unleash.go
  cmd/unleash_test.go
  configuration/configuration.go
  configuration/configuration_test.go
  configuration/mutantenabled.go
  configuration/mutantenables_test.go
  pkg/mutant/mutant.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/mutator/testdata/fixtures/0_all_go
Labels: s/XL

#83 fix: point to flag dash
  cmd/unleash.go
Labels: c/docs, s/XS
