Repository go-gremlins/gremlins, pull requests merged in 2022-09, with the labels that each got.

#159 mutant: add INVERT_LOOPCTRL mutation
  docs/docs/schema/configuration.json
  docs/docs/usage/commands/unleash/index.md
  docs/docs/usage/configuration.md
  docs/docs/usage/mutations/index.md
  docs/docs/usage/mutations/invert_loop.md
  docs/mkdocs.yml
  internal/configuration/mutantenabled.go
  internal/configuration/mutantenables_test.go
  internal/engine/engine_test.go
  internal/engine/mappings.go
  internal/engine/node.go
  internal/engine/node_test.go
  internal/engine/testdata/fixtures/loop_break_go
  internal/engine/testdata/fixtures/loop_continue_go
  internal/mutator/mutator.go
  internal/mutator/mutator_test.go
Labels: c/feature, s/L

#157 Replace hardlinks with a copy of the files
  internal/engine/tokenmutator.go
  internal/engine/workdir/testdata/filetocopy_go
  internal/engine/workdir/workdir.go
  internal/engine/workdir/workdir_test.go
Labels: c/bug, s/XXL

#161 Add "Invert Assignments" mutations
  cmd/unleash_test.go
  docs/docs/schema/configuration.json
  docs/docs/usage/commands/unleash/index.md
  docs/docs/usage/mutations/index.md
  docs/docs/usage/mutations/invert_assignments.md
  docs/mkdocs.yml
  internal/configuration/mutantenabled.go
  internal/configuration/mutantenables_test.go
  internal/engine/engine_test.go
  internal/engine/mappings.go
  internal/engine/node.go
  internal/engine/node_test.go
  internal/engine/testdata/fixtures/add_assign_go
  internal/engine/testdata/fixtures/mul_assign_go
  internal/engine/testdata/fixtures/quo_assign_go
  internal/engine/testdata/fixtures/rem_assign_go
  internal/engine/testdata/fixtures/sub_assign_go
  internal/mutator/mutator.go
  internal/mutator/mutator_test.go
Labels: c/feature, s/XL

#163 coverage: add support for flag --coverpkg
  cmd/unleash.go
  cmd/unleash_test.go
  docs/docs/schema/configuration.json
  docs/docs/usage/commands/unleash/index.md
  internal/configuration/configuration.go
  internal/coverage/coverage.go
  internal/coverage/coverage_test.go
Labels: c/feature, s/M

#168 mutant: add INVERT_BITWISE mutation
  cmd/unleash_test.go
  docs/docs/schema/configuration.json
  docs/docs/usage/commands/unleash/index.md
  docs/docs/usage/configuration.md
  docs/docs/usage/mutations/index.md
  docs/docs/usage/mutations/invert_bitwise.md
  docs/mkdocs.yml
  internal/configuration/mutantenabled.go
  internal/configuration/mutantenables_test.go
  internal/engine/engine_test.go
  internal/engine/mappings.go
  internal/engine/testdata/fixtures/and_go
  internal/engine/testdata/fixtures/and_not_go
  internal/engine/testdata/fixtures/illegal_go
  internal/engine/testdata/fixtures/or_go
  internal/engine/testdata/fixtures/shl_go
  internal/engine/testdata/fixtures/shr_go
  internal/engine/testdata/fixtures/xor_go
  internal/mutator/mutator.go
  internal/mutator/mutator_test.go
Labels: c/feature, s/L

#171 bug: fix unreliable results when using multiple workers
  internal/engine/executor.go
  internal/engine/executor_test.go
  internal/engine/stubs_test.go
  internal/engine/tokenmutator.go
  internal/engine/workerpool/workerpool_test.go
  internal/mutator/mutator.go
  internal/report/report_test.go
Labels: s/L
