Repository go-gremlins/gremlins, pull requests merged in 2022-08, with the labels that each got.

#89 docs: complete basic documentation
  docs/docs/index.md
  docs/docs/usage/commands/gremlins.md
  docs/docs/usage/commands/unleash.md
  docs/docs/usage/mutations/arithmetic_base.md
  docs/docs/usage/mutations/conditionals_boundary.md
  docs/docs/usage/mutations/conditionals_negation.md
  docs/docs/usage/mutations/increment_decrement.md
  docs/docs/usage/mutations/invert_negatives.md
  docs/mkdocs.yml
Labels: c/docs, s/L

#92 docs: fix formatting error
  docs/docs/usage/mutations/conditionals_boundary.md
  docs/docs/usage/mutations/conditionals_negation.md
  docs/docs/usage/mutations/increment_decrement.md
  docs/docs/usage/mutations/invert_negatives.md
Labels: c/docs, s/M

#94 docs: move contributing
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  README.md
  docs/CONTRIBUTING.md
  docs/docs/CONTRIBUTING.md
  docs/docs/index.md
  docs/docs/install.md
  docs/docs/usage/commands/index.md
  docs/docs/usage/mutations/index.md
  docs/mkdocs.yml
Labels: c/docs, s/M

#95 docs: fix contributing
  docs/CONTRIBUTING.md
  docs/docs/CONTRIBUTING.md
Labels: c/docs, s/L

#96 docs: fix default development version
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: c/docs, s/XS

#97 docs: add fancy icons
  docs/docs/install.md
Labels: c/docs, s/S

#98 docs: fix typo
  docs/docs/install.md
Labels: c/docs, s/XS

#99 docs: add JSON schema
  .github/workflows/docs.yml
  docs/docs/install.md
  docs/docs/schema/configuration.json
  docs/docs/usage/configuration.md
  docs/mkdocs.yml
Labels: c/docs, s/L

#100 docs: remove 'v' from version
  .github/workflows/release.yml
  docs/mkdocs.yml
Labels: c/docs, s/XS

#102 global: update to go1.19
  .github/workflows/ci.yml
  Makefile
  cmd/unleash.go
  configuration/configuration.go
  go.mod
  go.sum
  pkg/mutant/mutant.go
  pkg/mutant/mutant_test.go
  pkg/mutator/internal/tokenmutant_test.go
  pkg/mutator/mutator_test.go
Labels: c/enhancement, s/M

#103 coverage: optimize heavy lifting of parameters
  .github/workflows/ci.yml
  cmd/internal/flags/flags.go
  cmd/internal/flags/flags_test.go
  cmd/unleash.go
  pkg/coverage/coverage.go
  pkg/log/log.go
Labels: c/enhancement, s/M

#105 docs: add mascotte and logo
  README.md
  docs/docs/assets/images/favicon.png
  docs/docs/assets/images/gremlins_mascotte.png
  docs/docs/assets/images/logo.png
  docs/docs/index.md
  docs/docs/install.md
  docs/mkdocs.yml
Labels: c/docs, s/S

#106 global: align struct fields
  Makefile
  configuration/configuration_test.go
  internal/execution/execution_test.go
  pkg/coverage/profile_test.go
  pkg/mutant/mutant_test.go
  pkg/mutator/internal/node_test.go
  pkg/mutator/internal/tokenmutant.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/report/report_test.go
Labels: c/enhancement, s/L

#91 coverage: separate go download step
  pkg/coverage/coverage.go
  pkg/coverage/coverage_test.go
Labels: c/enhancement, s/M

#93 log: add silent mode
  cmd/gremlins.go
  cmd/gremlins_test.go
  cmd/internal/flags/flags.go
  cmd/internal/flags/flags_test.go
  configuration/configuration.go
  docs/docs/usage/commands/index.md
  docs/docs/usage/configuration.md
  pkg/log/log.go
  pkg/log/log_test.go
Labels: c/feature, s/L

#104 report: add JSON output to file
  cmd/unleash.go
  cmd/unleash_test.go
  configuration/configuration.go
  docs/docs/schema/configuration.json
  docs/docs/usage/commands/unleash.md
  docs/docs/usage/configuration.md
  pkg/coverage/coverage.go
  pkg/coverage/coverage_test.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/report/internal/structure.go
  pkg/report/report.go
  pkg/report/report_test.go
  pkg/report/testdata/normal_output.json
Labels: c/feature, s/XL

#110 global: add graceful shutdown
  cmd/gremlins.go
  cmd/gremlins/main.go
  cmd/gremlins/main_test.go
  cmd/gremlins_test.go
  cmd/unleash.go
  cmd/unleash_test.go
  configuration/configuration.go
  configuration/configuration_test.go
  pkg/coverage/coverage.go
  pkg/log/log.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/report/report.go
  pkg/report/report_test.go
Labels: c/enhancement, s/L

#111 docker: create docker image (#69)
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release.yml
  .goreleaser.yaml
  Dockerfile
  README.md
  docs/docs/install.md
  pkg/mutator/workdir/workdir.go
  pkg/mutator/workdir/workdir_test.go
Labels: s/L

#113 report: fix get as float if stored as int
  pkg/report/report.go
  pkg/report/report_test.go
Labels: c/bug, s/S

#114 release: make build reproducible
  .goreleaser.yaml
Labels: c/chore, s/XS

#115 ci: fix small release problems
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: c/chore, s/XS

#118 ci: add a gremlins step
  .github/workflows/gremlins.yml
Labels: c/chore, s/S

#117 docker: add arm64 to Docker release
  .goreleaser.yaml
Labels: c/chore, s/M

#119 refactor: make IsCovered more readable
  .golangci.yml
  pkg/coverage/profile.go
  pkg/coverage/profile_test.go
Labels: c/chore, s/L

#121 fix: config loading order
  configuration/configuration.go
  configuration/configuration_test.go
Labels: c/bug, s/M

#120 global: make gremlins work on packages
  .github/workflows/gremlins.yml
  cmd/gremlins_test.go
  cmd/unleash.go
  cmd/unleash_test.go
  configuration/configuration.go
  configuration/configuration_test.go
  configuration/mutantenables_test.go
  configuration/testdata/config1/go.mod
  docs/docs/index.md
  docs/docs/usage/configuration.md
  internal/gomodule/gomodule.go
  internal/gomodule/gomodule_test.go
  pkg/coverage/coverage.go
  pkg/coverage/coverage_test.go
  pkg/coverage/testdata/valid/coverage
  pkg/mutator/internal/node_test.go
  pkg/mutator/internal/tokenmutant_test.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/mutator/workdir/workdir_test.go
Labels: c/feature, s/XL

#122 docs: fix source install instruction
  docs/docs/install.md
Labels: s/XS

#123 mutator: fix resource leakage
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
Labels: c/bug, s/XS

#125 global: make tests run on packages by default
  cmd/unleash.go
  cmd/unleash_test.go
  configuration/configuration.go
  docs/docs/index.md
  docs/docs/usage/commands/unleash.md
  docs/docs/usage/configuration.md
  internal/gomodule/gomodule.go
  internal/gomodule/gomodule_test.go
  pkg/coverage/coverage.go
  pkg/coverage/coverage_test.go
  pkg/mutant/mutant.go
  pkg/mutator/internal/tokenmutant.go
  pkg/mutator/internal/tokenmutant_test.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/report/report_test.go
Labels: c/feature, s/XL

#128 docs: add animated gif
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/docs/assets/images/gremlins-term.webp
  docs/docs/index.md
Labels: c/docs, s/XS

#131 ci: add gremlins action step
  .github/workflows/ci.yml
  .github/workflows/gremlins.yml
Labels: c/chore, s/S

#132 ci: update gremlins-actions
  .github/workflows/gremlins.yml
  docs/docs/usage/ci/docker.md
  docs/docs/usage/ci/github-action.md
  docs/mkdocs.yml
Labels: c/chore, s/M

#127 global: enable parallel execution
  cmd/internal/flags/flags.go
  cmd/internal/flags/flags_test.go
  cmd/unleash.go
  cmd/unleash_test.go
  configuration/configuration.go
  docs/docs/usage/commands/unleash/index.md
  docs/docs/usage/commands/unleash/workers.md
  docs/docs/usage/configuration.md
  docs/mkdocs.yml
  pkg/mutator/executor.go
  pkg/mutator/executor_test.go
  pkg/mutator/internal/tokenmutant.go
  pkg/mutator/internal/tokenmutant_test.go
  pkg/mutator/internal/workerpool/workerpool.go
  pkg/mutator/internal/workerpool/workerpool_test.go
  pkg/mutator/mutator.go
  pkg/mutator/mutator_test.go
  pkg/mutator/stubs_test.go
  pkg/mutator/workdir/workdir.go
  pkg/mutator/workdir/workdir_test.go
Labels: c/enhancement, s/XXL

#135 docs: use shields.io where possible
  README.md
Labels: c/docs, s/XS

#141 cmd: use heredoc
  cmd/gremlins.go
  cmd/unleash.go
  go.mod
  go.sum
Labels: c/chore, s/M

#143 coverage: print combined output in case of failure
  pkg/coverage/coverage.go
  pkg/mutator/mutator.go
Labels: c/enhancement, s/S

#147 ci: run on every PR
  .github/workflows/ci.yml
Labels: c/chore, s/XS

#146 Add invert logical operations mutator
  configuration/mutantenabled.go
  configuration/mutantenables_test.go
  docs/docs/usage/commands/unleash/index.md
  docs/docs/usage/configuration.md
  docs/docs/usage/mutations/index.md
  docs/docs/usage/mutations/invert_logical.md
  docs/mkdocs.yml
  pkg/mutant/mutant.go
  pkg/mutant/mutant_test.go
  pkg/mutator/internal/mappings.go
  pkg/mutator/mutator_test.go
  pkg/mutator/testdata/fixtures/land_go
  pkg/mutator/testdata/fixtures/lor_go
Labels: c/feature, s/L

#148 docs: fix escapings
  docs/docs/usage/mutations/conditionals_negation.md
  docs/docs/usage/mutations/invert_logical.md
Labels: c/docs, s/M

#149 chore: maintain CI and templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  .github/workflows/ci.yml
  .github/workflows/gremlins.yml
Labels: c/chore, s/M

#152 ci: trigger docs build only for main branch
  .github/workflows/ci.yml
Labels: c/chore, s/XS

#151 mutant: refactor to respect Go convention
  cmd/unleash.go
  cmd/unleash_test.go
  pkg/mutant/mutant.go
  pkg/mutator/mutator_test.go
  pkg/mutator/stubs_test.go
Labels: s/S, c/refactoring

#153 ci: fix CI wasting workflows
  .github/workflows/ci.yml
Labels: c/chore, s/XS

#154 ci: fix CI wasting gremlins workflows for Gremlins
  .github/workflows/gremlins.yml
Labels: s/XS

#150 config: prevent mutants not tested for default
  configuration/mutantenables_test.go
Labels: s/S, c/refactoring

#155 ci: update golangci-lint
  .golangci.yml
Labels: c/chore, s/M
