Repository go-gremlins/gremlins, pull requests merged in 2022-10, with the labels that each got.

#179 60 remove assignments
  cmd/unleash_test.go
  docs/docs/schema/configuration.json
  docs/docs/usage/commands/unleash/index.md
  docs/docs/usage/configuration.md
  docs/docs/usage/mutations/index.md
  docs/docs/usage/mutations/invert_assignments.md
  docs/docs/usage/mutations/remove_self_assignments.md
  docs/mkdocs.yml
  internal/configuration/mutantenabled.go
  internal/configuration/mutantenables_test.go
  internal/engine/engine_test.go
  internal/engine/mappings.go
  internal/engine/testdata/fixtures/and_assign_go
  internal/engine/testdata/fixtures/and_not_assign_go
  internal/engine/testdata/fixtures/or_assign_go
  internal/engine/testdata/fixtures/shl_assign_go
  internal/engine/testdata/fixtures/shr_assign_go
  internal/engine/testdata/fixtures/xor_assign_go
  internal/mutator/mutator.go
  internal/mutator/mutator_test.go
Labels: c/feature, s/L

#181 mutant: add INVERT_BWASSIGN mutant
  cmd/unleash_test.go
  docs/docs/schema/configuration.json
  docs/docs/usage/commands/unleash/index.md
  docs/docs/usage/configuration.md
  docs/docs/usage/mutations/index.md
  docs/docs/usage/mutations/invert_bitwise_assignments.md
  docs/mkdocs.yml
  internal/configuration/mutantenabled.go
  internal/configuration/mutantenables_test.go
  internal/engine/engine_test.go
  internal/engine/mappings.go
  internal/mutator/mutator.go
  internal/mutator/mutator_test.go
Labels: c/feature, s/L

#183 Use GOTMPDIR env to clean all the go-build folders
  internal/engine/executor.go
  internal/engine/executor_test.go
  internal/engine/stubs_test.go
  internal/engine/workdir/workdir.go
  internal/engine/workdir/workdir_test.go
Labels: c/enhancement, s/M

#185 reports: add type statistics to report file
  internal/report/internal/structure.go
  internal/report/report.go
  internal/report/report_test.go
  internal/report/testdata/normal_output.json
Labels: c/feature, s/L

#190 docs: fix documentation formatting
  docs/docs/usage/commands/unleash/index.md
Labels: c/docs, s/XS

#192 Fix working directory of the test cmd when integration mode is set (#…
  internal/engine/executor.go
  internal/engine/executor_test.go
  internal/engine/stubs_test.go
Labels: c/bug, s/M
